Migrate to Go 1.11
EXCCoin/exccd pull request #48
Opened 2018-12-17 12:18 UTC by jksf

2018-12-20 12:02 UTC, harzo approved these changes

2018-12-20 13:41 UTC, harzo requested changes
Please, rebase this branch with master :)

2018-12-21 13:04 UTC, jksf commented
Done

2018-12-21 13:30 UTC, harzo submitted a review, later dismissed

2018-12-21 14:39 UTC, harzo approved these changes

2018-12-21 15:01 UTC, merged